name: Release build
on:
  pull_request:
    types: [opened, synchronize, reopened, labeled]

jobs:
  win_build:
    name: Windows Latest x64
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0
      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          version: '5.12.3'
      - name: Configure test project on windows
        run: |
          echo on
          call "%programfiles(x86)%\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
          qmake
        shell: cmd
      - name: Build
        run: |
          echo on
          call "%programfiles(x86)%\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
          nmake check
        shell: cmd
