name: Run tests
on:
  pull_request:
    types: [opened, synchronize, reopened, labeled]

jobs:

  run_tests:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0
      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          version: '5.12.3'
      - name: Check
        run: pwd
      - name: Configure
        run: qmake simple_qt_tests_ci.pro
      - name: Build tests
        run: make
      - name: Run tests
        run: make check
