name: Run tests
on:
  pull_request:
    types: [opened, synchronize, reopened, labeled]

jobs:
  run_tests:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0
      - name: Prepare Deps and Local folders
        run: |
          mkdir -p ${{ github.workspace }}/../deps
          mkdir -p ${{ github.workspace }}/../local
      - name: Install gRPC
        run: |
          cd ${{ github.workspace }}/../deps
          git clone https://github.com/grpc/grpc --branch v1.33.2 --depth 1
          cd grpc
          git submodule update --init --recursive
          mkdir -p cmake/build
          cd cmake/build
          cmake ../.. -DDBUILD_SHARED_LIBS=ON -DCMAKE_INSTALL_PREFIX=${{ github.workspace }}/../local
          make -j$(nproc)
          make install
      - name: MongoDB C Driver
        run: |
          cd ${{ github.workspace }}/../deps
          sudo apt-get install -y libssl-dev libsasl2-dev wget
          TAG=1.17.2
          wget "https://github.com/mongodb/mongo-c-driver/releases/download/$TAG/mongo-c-driver-$TAG.tar.gz"
          tar xzf "mongo-c-driver-$TAG.tar.gz"
          cd "mongo-c-driver-$TAG" 
          mkdir cmake-build && cd cmake-build
          cmake -DCMAKE_BUILD_TYPE=Release \
           -DENABLE_ICU=OFF \
           -DENABLE_AUTOMATIC_INIT_AND_CLEANUP=OFF \
           -DCMAKE_INSTALL_PREFIX=${{ github.workspace }}/../local \
           ..
          make -j$(nproc) install
      - name: MongoDB CXX Driver
        run: |
          cd ${{ github.workspace }}/../deps
          git clone https://github.com/mongodb/mongo-cxx-driver.git --branch r3.6.1 --depth 1
          cd mongo-cxx-driver/build
          cmake -DCMAKE_BUILD_TYPE=Release \
                -DCMAKE_INSTALL_PREFIX=${{ github.workspace }}/../local \
                -DBUILD_SHARED_LIBS=OFF ..
          make -j$(nproc) install
      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          version: '5.12.3'
      - name: Check
        run: pwd
      - name: Configure
        run: qmake simple_qt_tests_ci.pro
      - name: Build tests
        run: make
      - name: Run tests
        run: make check
