name: Run tests
on:
  pull_request:
    types: [opened, synchronize, reopened, labeled]

jobs:
  run_tests:
    runs-on: [self-hosted, linux]
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0
      - name: Run Docked build
        run: |
          docker build -t simple_qt_tests_ci -f Dockerfile .
